<?php

namespace SAV\ProcessBundle\Repository;

/**
 * CentreSavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreSavRepository extends \Doctrine\ORM\EntityRepository
{
}
