<?php

namespace SAV\ProcessBundle\Repository;

/**
 * MotifAnnulationReparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotifAnnulationReparationRepository extends \Doctrine\ORM\EntityRepository
{
}
