<?php

namespace SAV\ProcessBundle\Repository;

/**
 * MotifRefusProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotifRefusProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
