<?php

namespace SAV\ProcessBundle\Repository;

/**
 * MouvementStockProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementStockProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
