<?php

namespace SAV\ProcessBundle\Repository;

/**
 * MouvementStockPieceDetacheeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MouvementStockPieceDetacheeRepository extends \Doctrine\ORM\EntityRepository
{
}
