<?php

namespace SAV\ProcessBundle\Repository;

/**
 * ParcoursProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParcoursProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
