<?php

namespace SAV\ProcessBundle\Repository;

/**
 * PieceDetacheeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceDetacheeRepository extends \Doctrine\ORM\EntityRepository
{
}
