<?php

namespace SAV\ProcessBundle\Repository;

/**
 * RubriqueProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubriqueProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
