<?php

namespace SAV\ProcessBundle\Repository;

/**
 * StatutReparationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutReparationRepository extends \Doctrine\ORM\EntityRepository
{
}
