<?php

namespace SAV\ProcessBundle\Repository;

/**
 * StatutTraitementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutTraitementRepository extends \Doctrine\ORM\EntityRepository
{
}
