<?php

namespace SAV\ProcessBundle\Repository;

/**
 * StatutPieceDetacheeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutPieceDetacheeRepository extends \Doctrine\ORM\EntityRepository
{
}
