<?php

namespace SAV\ProcessBundle\Repository;

/**
 * StatutReceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutReceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
