<?php

namespace SAV\ProcessBundle\Repository;

/**
 * TransporteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransporteurRepository extends \Doctrine\ORM\EntityRepository
{
}
